generate_mission_plan:
  description: >
    Recall the sequence of steps to complete an assigned mission, {mission} from training data about flight operations.
  expected_output: >
    A chronological list of operations necessary to complete a mission.
  agent: mission_manager
  allow_delegation: false

recall_task_organization:
  description: >
    Recall the roles and responsibilities for each agent in the U-28A Flight Crew by consulting AFMAN 11-2U-28A,
    Volumes 1, 2, and 3.
  expected_output: >
    Name of each agent followed by a list of the operations in the mission plan for which they are responsible.
  agent: mission_manager
  allow_delegation: false

assign_roles_sequentially:
  description: >
    Delegate one operation at a time to each agent, based on the chronological order in which it takes place.

    Each time you delegate, prompt the agent to follow a 4 task process:
    
    {task_delegation}

  expected_output: >
    Delegate the task to the appropriate agent.
  agent: mission_manager

generate_operations_instructions:
  description: >
    Recall the substeps necessary to complete a specific assigned operation within the mission plan from training data.
  expected_output: >
    A list of subtasks in chronological order to complete an operation.
  agent: ground_station_operator

iterate_on_instructions:
  description: >
    Compare operations instructions against instructions in the relevant policy and refine if necessary.
  expected_output: >
    A refined list of subtasks in chronological order with revisions if necessary.
  agent: ground_station_operator

generate_success_checklist:
  description: >
    Specify the condition that must be met after each subtask to advance to the next step.
  expected_output: >
    A checklist matching one success condition to each subtask.
  agent: ground_station_operator

execute_operation:
  description: >
    Narrate as each subtask is completed and observe the fulfillment of the required conditions to proceed to the next step.
  expected_output: >
    A concise expression of each subtask and acknowledgment that the required condition has been met for each step.
  agent: ground_station_operator

generate_operations_instructions_pilot:
  description: >
    Recall the substeps necessary to complete a specific assigned operation within the mission plan from training data.
  expected_output: >
    A list of subtasks in chronological order to complete an operation.
  agent: pilot

iterate_on_instructions_pilot:
  description: >
    Compare operations instructions against instructions in AFMANs Vols 1, 2, 3 and the PC-12/45 Pilot’s Operating Handbook, refining operations instructions only if necessary.
  expected_output: >
    A list of subtasks in chronological order with revisions if necessary.
  agent: pilot

generate_success_checklist_pilot:
  description: >
    Specify the condition that must be met after each subtask to advance to the next step.
  expected_output: >
    A checklist matching one success condition to each subtask.
  agent: pilot

execute_operation_pilot:
  description: >
    Narrate as each subtask is completed and observe the fulfillment of the required conditions to proceed to the next step.
  expected_output: >
    A concise expression of each subtask and acknowledgment that the required condition has been met for each step.
  agent: pilot

generate_operations_instructions_co_pilot:
  description: >
    Recall the substeps necessary to complete a specific assigned operation within the mission plan from training data.
  expected_output: >
    A list of subtasks in chronological order to complete an operation.
  agent: co_pilot

iterate_on_instructions_co_pilot:
  description: >
    Compare operations instructions against instructions in AFMANs Vols 1, 2, 3 and the PC-12/45 Pilot’s Operating Handbook, and the Multi-Service Brevity code guide, refining operations instructions only if necessary.
  expected_output: >
    A list of subtasks in chronological order with revisions if necessary.
  agent: co_pilot

generate_success_checklist_co_pilot:
  description: >
    Specify the condition that must be met after each subtask to advance to the next step.
  expected_output: >
    A checklist matching one success condition to each subtask.
  agent: co_pilot

execute_operation_co_pilot:
  description: >
    Narrate as each subtask is completed and observe the fulfillment of the required conditions to proceed to the next step.
  expected_output: >
    A concise expression of each subtask and acknowledgment that the required condition has been met for each step.
  agent: co_pilot

generate_operations_instructions_combat_system_officer:
  description: >
    Recall the substeps necessary to complete a specific assigned operation within the mission plan from training data.
  expected_output: >
    A list of subtasks in chronological order to complete an operation.
  agent: combat_system_officer

iterate_on_instructions_combat_system_officer:
  description: >
    Compare operations instructions against instructions in AFMANs Vols 1, 2, 3, refining operations instructions only if necessary.
  expected_output: >
    A list of subtasks in chronological order with revisions if necessary.
  agent: combat_system_officer

generate_success_checklist_combat_system_officer:
  description: >
    Specify the condition that must be met after each subtask to advance to the next step.
  expected_output: >
    A checklist matching one success condition to each subtask.
  agent: combat_system_officer

execute_operation_combat_system_officer:
  description: >
    Narrate as each subtask is completed and observe the fulfillment of the required conditions to proceed to the next step.
  expected_output: >
    A concise expression of each subtask and acknowledgment that the required condition has been met for each step.
  agent: combat_system_officer